const items = [
  {
    image: "./thumbs/D001-vol.jpg",
    alt: "D001 vol",
    text: "Item 1",
    href: "./shows/01-sign-up/index.html",
  },
  {
    image: "./thumbs/D002-ck-out.jpg",
    alt: "D002 ck out",
    text: "Item 2",
    href: "./shows/02-checkout/index.html",
  },
  {
    image: "./thumbs/D003-landing.jpg",
    alt: "D003 landing",
    text: "Item 3",
    href: "./shows/03-landing/index.html",
  },
  {
    image: "./thumbs/D004-calc.jpg",
    alt: "D004 calc",
    text: "Item 4",
    href: "./shows/04-calculator/index.html",
  },
  {
    image: "./thumbs/D005-icon.jpg",
    alt: "D005 icon",
    text: "Item 5",
    href: "./shows/05-icon/index.html",
  },
  {
    image: "./thumbs/D006-user-profile.jpg",
    alt: "D006 user profile",
    text: "Item 6",
    href: "./shows/06-user/index.html",
  },
  {
    image: "./thumbs/D007-settings.jpg",
    alt: "D007 settings",
    text: "Item 7",
    href: "./shows/07-settings/index.html",
  },
  {
    image: "./thumbs/D008-404-er.jpg",
    alt: "D008 404 er",
    text: "Item 8",
    href: "./shows/08-404/index.html",
  },
  {
    image: "./thumbs/D009-music.jpg",
    alt: "D009 music",
    text: "Item 9",
    href: "./shows/09-music/index.html",
  },
  {
    image: "./thumbs/D010-social.jpg",
    alt: "D010 social",
    text: "Item 10",
    href: "./shows/10-social/index.html",
  },
  {
    image: "./thumbs/D011-flsh.jpg",
    alt: "D011 flsh",
    text: "Item 11",
    href: "./shows/100-redesign-flt-search/index.html",
  },
  {
    image: "./thumbs/D012-ecom.jpg",
    alt: "D012 ecom",
    text: "Item 12",
    href: "./shows/108-quote/index.html",
  },
  {
    image: "./thumbs/D013-dirmsg.jpg",
    alt: "D013 dirmsg",
    text: "Item 13",
    href: "./shows/11-flsh-msg/index.html",
  },
  {
    image: "./thumbs/D014-countdown.jpg",
    alt: "D014 countdown",
    text: "Item 14",
    href: "./shows/12-ecom/index.html",
  },
  {
    image: "./thumbs/D015-switch.jpg",
    alt: "D015 switch",
    text: "Item 15",
    href: "./shows/13-dir-msg/index.html",
  },
  {
    image: "./thumbs/D016-overlay.jpg",
    alt: "D016 overlay",
    text: "Item 16",
    href: "./shows/14-count-dwn/index.html",
  },
  {
    image: "./thumbs/D017-receipt.jpg",
    alt: "D017 receipt",
    text: "Item 17",
    href: "./shows/15-switch/index.html",
  },
  {
    image: "./thumbs/D018-chart.jpg",
    alt: "D018 chart",
    text: "Item 18",
    href: "./shows/16-pop up overlay/index.html",
  },
  {
    image: "./thumbs/D019-leader.jpg",
    alt: "D019 leader",
    text: "Item 19",
    href: "./shows/17-receipt/index.html",
  },
  {
    image: "./thumbs/D020-location.jpg",
    alt: "D020 location",
    text: "Item 20",
    href: "./shows/18-analytics chart/index.html",
  },
  {
    image: "./thumbs/D021-home-dash.jpg",
    alt: "D021 home dash",
    text: "Item 21",
    href: "./shows/19-leaderboard/index.html",
  },
  {
    image: "./thumbs/D022-search.jpg",
    alt: "D022 search",
    text: "Item 22",
    href: "./shows/20-location/index.html",
  },
  {
    image: "./thumbs/D023-onboard.jpg",
    alt: "D023 onboard",
    text: "Item 23",
    href: "./shows/21-home-dash/index.html",
  },
  {
    image: "./thumbs/D024-boarding-pass.jpg",
    alt: "D024 boarding pass",
    text: "Item 24",
    href: "./shows/22-search/index.html",
  },
  {
    image: "./thumbs/D025-TV-app.jpg",
    alt: "D025 TV app",
    text: "Item 25",
    href: "./shows/23-onboard/index.html",
  },
  {
    image: "./thumbs/D026-subscribe.jpg",
    alt: "D026 subscribe",
    text: "Item 26",
    href: "./shows/24-boarding-pass/index.html",
  },
  {
    image: "./thumbs/D027-dropdown.jpg",
    alt: "D027 dropdown",
    text: "Item 27",
    href: "./shows/25-television/index.html",
  },
  {
    image: "./thumbs/D028-map-mob.jpg",
    alt: "D028 map mob",
    text: "Item 28",
    href: "./shows/26-subscribe/index.html",
  },
  {
    image: "./thumbs/D029-contact-mob.jpg",
    alt: "D029 contact mob",
    text: "Item 29",
    href: "./shows/27-dropdown/index.html",
  },
  {
    image: "./thumbs/D030-pricing.jpg",
    alt: "D030 pricing",
    text: "Item 30",
    href: "./shows/28-map/index.html",
  },
  {
    image: "./thumbs/D031-upload.jpg",
    alt: "D031 upload",
    text: "Item 31",
    href: "./shows/29-contact/index.html",
  },
  {
    image: "./thumbs/D032-crowd.jpg",
    alt: "D032 crowd",
    text: "Item 32",
    href: "./shows/30-pricing/index.html",
  },
  {
    image: "./thumbs/D033-cust-prd.jpg",
    alt: "D033 cust prd",
    text: "Item 33",
    href: "./shows/31-upload/index.html",
  },
  {
    image: "./thumbs/D034-car.jpg",
    alt: "D034 car",
    text: "Item 34",
    href: "./shows/32-crowdfunding/index.html",
  },
  {
    image: "./thumbs/D035-blog.jpg",
    alt: "D035 blog",
    text: "Item 35",
    href: "./shows/33-customize/index.html",
  },
  {
    image: "./thumbs/D036-offer.jpg",
    alt: "D036 offer",
    text: "Item 36",
    href: "./shows/34-car-inteface/index.html",
  },
  {
    image: "./thumbs/D037-weather.jpg",
    alt: "D037 weather",
    text: "Item 37",
    href: "./shows/35-blog/index.html",
  },
  {
    image: "./thumbs/D038-calendar.jpg",
    alt: "D038 calendar",
    text: "Item 38",
    href: "./shows/36-special-offer/index.html",
  },
  {
    image: "./thumbs/D039-testimonial.jpg",
    alt: "D039 testimonial",
    text: "Item 39",
    href: "./shows/37-weather/index.html",
  },
  {
    image: "./thumbs/D040-recipe.jpg",
    alt: "D040 recipe",
    text: "Item 40",
    href: "./shows/38-calendar/index.html",
  },
  {
    image: "./thumbs/D041-exercise.jpg",
    alt: "D041 exercise",
    text: "Item 41",
    href: "./shows/39-testimonial/index.html",
  },
  {
    image: "./thumbs/D042-todo.jpg",
    alt: "D042 todo",
    text: "Item 42",
    href: "./shows/40-recipe/index.html",
  },
  {
    image: "./thumbs/D043-menu.jpg",
    alt: "D043 menu",
    text: "Item 43",
    href: "./shows/41-exercise/index.html",
  },
  {
    image: "./thumbs/D044-favs.jpg",
    alt: "D044 favs",
    text: "Item 44",
    href: "./shows/42-todo/index.html",
  },
  {
    image: "./thumbs/D045-info.jpg",
    alt: "D045 info",
    text: "Item 45",
    href: "./shows/43-food-menu/index.html",
  },
  {
    image: "./thumbs/D046-invoice.jpg",
    alt: "D046 invoice",
    text: "Item 46",
    href: "./shows/44-favorites/index.html",
  },
  {
    image: "./thumbs/D047-activity.jpg",
    alt: "D047 activity",
    text: "Item 47",
    href: "./shows/45-info-card/index.html",
  },
  {
    image: "./thumbs/D048-soon.jpg",
    alt: "D048 soon",
    text: "Item 48",
    href: "./shows/46-invoice/index.html",
  },
  {
    image: "./thumbs/D049-notification.jpg",
    alt: "D049 notification",
    text: "Item 49",
    href: "./shows/47-activity-feed/index.html",
  },
  {
    image: "./thumbs/D050-job.jpg",
    alt: "D050 job",
    text: "Item 50",
    href: "./shows/48-coming-soon/index.html",
  },
  {
    image: "./thumbs/D051-press-page.jpg",
    alt: "D051 press page",
    text: "Item 51",
    href: "./shows/49-notification/index.html",
  },
  {
    image: "./thumbs/D052-logo-design.jpg",
    alt: "D052 logo design",
    text: "Item 52",
    href: "./shows/50-job/index.html",
  },
  {
    image: "./thumbs/D053-nav-bar.jpg",
    alt: "D053 nav bar",
    text: "Item 53",
    href: "./shows/51-press-page/index.html",
  },
  {
    image: "./thumbs/D054-confirm.jpg",
    alt: "D054 confirm",
    text: "Item 54",
    href: "./shows/52-logo/index.html",
  },
  {
    image: "./thumbs/D055-icon-set.jpg",
    alt: "D055 icon set",
    text: "Item 55",
    href: "./shows/53-navigation/index.html",
  },
  {
    image: "./thumbs/D056-breadcrumbs.jpg",
    alt: "D056 breadcrumbs",
    text: "Item 56",
    href: "./shows/54-confirmation/index.html",
  },
  {
    image: "./thumbs/D057-video-player.jpg",
    alt: "D057 video player",
    text: "Item 57",
    href: "./shows/55-icon-set/index.html",
  },
  {
    image: "./thumbs/D058-shopping-cart.jpg",
    alt: "D058 shopping cart",
    text: "Item 58",
    href: "./shows/56-breadcrumbs/index.html",
  },
  {
    image: "./thumbs/D059-background.jpg",
    alt: "D059 background",
    text: "Item 59",
    href: "./shows/57-video-player/index.html",
  },
  {
    image: "./thumbs/D060-color-picker.jpg",
    alt: "D060 color picker",
    text: "Item 60",
    href: "./shows/58-shopping-cart/index.html",
  },
  {
    image: "./thumbs/D061-redeem-cupon.jpg",
    alt: "D061 redeem cupon",
    text: "Item 61",
    href: "./shows/59-background/index.html",
  },
  {
    image: "./thumbs/D062-workout.jpg",
    alt: "D062 workout",
    text: "Item 62",
    href: "./shows/60-color-picker/index.html",
  },
  {
    image: "./thumbs/D063-best-of.jpg",
    alt: "D063 best of",
    text: "Item 63",
    href: "./shows/61-redeem-coupon/index.html",
  },
  {
    image: "./thumbs/D064-use-select.jpg",
    alt: "D064 use select",
    text: "Item 64",
    href: "./shows/62-workout-of-day/index.html",
  },
  {
    image: "./thumbs/D065-notes.jpg",
    alt: "D065 notes",
    text: "Item 65",
    href: "./shows/63-best-of/index.html",
  },
  {
    image: "./thumbs/D066-statistics.jpg",
    alt: "D066 statistics",
    text: "Item 66",
    href: "./shows/64-user-selection/index.html",
  },
  {
    image: "./thumbs/D067-home-rental.jpg",
    alt: "D067 home rental",
    text: "Item 67",
    href: "./shows/65-notes/index.html",
  },
  {
    image: "./thumbs/D068-flight-search.jpg",
    alt: "D068 flight search",
    text: "Item 68",
    href: "./shows/66-statistics/index.html",
  },
  {
    image: "./thumbs/D069-trending.jpg",
    alt: "D069 trending",
    text: "Item 69",
    href: "./shows/67-home-rental/index.html",
  },
  {
    image: "./thumbs/D070-event.jpg",
    alt: "D070 event",
    text: "Item 70",
    href: "./shows/68-flight-search/index.html",
  },
  {
    image: "./thumbs/D071-schedling.jpg",
    alt: "D071 schedling",
    text: "Item 71",
    href: "./shows/69-trending/index.html",
  },
  {
    image: "./thumbs/D072-carousel-sldier.jpg",
    alt: "D072 carousel sldier",
    text: "Item 72",
    href: "./shows/70-event-list/index.html",
  },
  {
    image: "./thumbs/D072-slide-mouseover.jpg",
    alt: "D072 slide mouseover",
    text: "Item 73",
    href: "./shows/71-scheduling/index.html",
  },
  {
    image: "./thumbs/D073-vr.jpg",
    alt: "D073 vr",
    text: "Item 74",
    href: "./shows/72-carousel/index.html",
  },
  {
    image: "./thumbs/D074-download.jpg",
    alt: "D074 download",
    text: "Item 75",
    href: "./shows/72-slide-on-mouse/index.html",
  },
  {
    image: "./thumbs/D075-pre-ord.jpg",
    alt: "D075 pre ord",
    text: "Item 76",
    href: "./shows/73-vr/index.html",
  },
  {
    image: "./thumbs/D076-load-snowman.jpg",
    alt: "D076 load snowman",
    text: "Item 77",
    href: "./shows/74-download/index.html",
  },
  {
    image: "./thumbs/D076-loading.jpg",
    alt: "D076 loading",
    text: "Item 78",
    href: "./shows/75-pre-ord/index.html",
  },
  {
    image: "./thumbs/D077-thankyou.jpg",
    alt: "D077 thankyou",
    text: "Item 79",
    href: "./shows/76-load-snow/index.html",
  },
  {
    image: "./thumbs/D078-invitation.jpg",
    alt: "D078 invitation",
    text: "Item 80",
    href: "./shows/76-loading/index.html",
  },
  {
    image: "./thumbs/D079-itinerary-mobile.jpg",
    alt: "D079 itinerary mobile",
    text: "Item 81",
    href: "./shows/77-thankyou/index.html",
  },
  {
    image: "./thumbs/D079-itinerary.jpg",
    alt: "D079 itinerary",
    text: "Item 82",
    href: "./shows/78-invitation/index.html",
  },
  {
    image: "./thumbs/D080-date-picker.jpg",
    alt: "D080 date picker",
    text: "Item 83",
    href: "./shows/79-itinerary/index.html",
  },
  {
    image: "./thumbs/D081-status-update.jpg",
    alt: "D081 status update",
    text: "Item 84",
    href: "./shows/79-itinerary-mobile/index.html",
  },
  {
    image: "./thumbs/D082-forms.jpg",
    alt: "D082 forms",
    text: "Item 85",
    href: "./shows/80-date-picker/index.html",
  },
  {
    image: "./thumbs/D083-button.jpg",
    alt: "D083 button",
    text: "Item 86",
    href: "./shows/81-status-update/index.html",
  },
  {
    image: "./thumbs/D084-badge.jpg",
    alt: "D084 badge",
    text: "Item 87",
    href: "./shows/82-forms/index.html",
  },
  {
    image: "./thumbs/D085-pagination.jpg",
    alt: "D085 pagination",
    text: "Item 88",
    href: "./shows/83-button/index.html",
  },
  {
    image: "./thumbs/D086-progress.jpg",
    alt: "D086 progress",
    text: "Item 89",
    href: "./shows/84-badge/index.html",
  },
  {
    image: "./thumbs/D087-tooltip.jpg",
    alt: "D087 tooltip",
    text: "Item 90",
    href: "./shows/85-pagination/index.html",
  },
  {
    image: "./thumbs/D088-avatar.jpg",
    alt: "D088 avatar",
    text: "Item 91",
    href: "./shows/86-progress/index.html",
  },
  {
    image: "./thumbs/D089-agree.jpg",
    alt: "D089 agree",
    text: "Item 92",
    href: "./shows/87-tooltip/index.html",
  },
  {
    image: "./thumbs/D090-create-new.jpg",
    alt: "D090 create new",
    text: "Item 93",
    href: "./shows/88-avatar/index.html",
  },
  {
    image: "./thumbs/D091-curated.jpg",
    alt: "D091 curated",
    text: "Item 94",
    href: "./shows/89-agree/index.html",
  },
  {
    image: "./thumbs/D092-faq.jpg",
    alt: "D092 faq",
    text: "Item 95",
    href: "./shows/90-create/index.html",
  },
  {
    image: "./thumbs/D093-splash.jpg",
    alt: "D093 splash",
    text: "Item 96",
    href: "./shows/91-curated/index.html",
  },
  {
    image: "./thumbs/D094-news.jpg",
    alt: "D094 news",
    text: "Item 97",
    href: "./shows/92-faq/index.html",
  },
  {
    image: "./thumbs/D095-product-tour.jpg",
    alt: "D095 product tour",
    text: "Item 98",
    href: "./shows/93-splash/index.html",
  },
  {
    image: "./thumbs/D096-in-stock.jpg",
    alt: "D096 in stock",
    text: "Item 99",
    href: "./shows/94-news/index.html",
  },
  {
    image: "./thumbs/D097-giveaway.jpg",
    alt: "D097 giveaway",
    text: "Item 100",
    href: "./shows/95-product-tour/index.html",
  },
  {
    image: "./thumbs/D098-ad.jpg",
    alt: "D098 ad",
    text: "Item 101",
    href: "./shows/96-in-stock/index.html",
  },
  {
    image: "./thumbs/D099-categories-side.jpg",
    alt: "D099 categories side",
    text: "Item 102",
    href: "./shows/97-giveaway/index.html",
  },
  {
    image: "./thumbs/D099-categories.jpg",
    alt: "D099 categories",
    text: "Item 103",
    href: "./shows/98-advertisement/index.html",
  },
  {
    image: "./thumbs/D100-flt-search-mob.jpg",
    alt: "D100 flt search mob",
    text: "Item 104",
    href: "./shows/99-categories/index.html",
  },
  {
    image: "./thumbs/D108-quote.jpg",
    alt: "D108 quote",
    text: "Item 105",
    href: "./shows/99b-categories-sidebar/index.html",
  },
];
